baseurl: https://valinsky.me
languageCode: en-us
title: Valinsky
theme: hello-friend-ng
author:
  name: Vali Voicu
# googleAnalytics: UA-151935413-1
# copyright: ''
# paginate: 10
enableRobotsTXT: true
canonifyURLs: true
# permalinks:
#   posts: /blog/:title/

params:
  # Directory name of your blog content (default is `content/posts`)
  contentTypeName: articles
  # Default theme "light" or "dark"
  defaultTheme: dark

  headTitle: Valinsky
  homeSubtitle: Senior Software Engineer

  # Metadata mostly used in document's head
  title: Valinsky
  description: Valinsky
  keywords: homepage, blog, programming, software

  images:
    - /images/triangle.jpg

  favicon:
    color:
      mask: "#252627"
      msapplication: "#252627"
      theme: "#252627"

  logo:
    logoText: cd /blog/
    logoHomeLink: /
  
  social:
    - name: github
      url: https://github.com/valinsky
    - name: email
      url: mailto:blog@valinsky.me

  # date format
  dateform: 2 Jan, 2006
  dateformShort: 2 Jan
  dateformNum: 02-01-2006
  dateformNumTime: 02-01-2006

menu:
  main:
    - identifier: articles
      name: articles
      url: /articles
      weight: -110
    # - identifier: about
    #   name: about
    #   url: /about
    #   weight: -100
